### ISSUE TITLE
[HELP] Failed to build module example with mips-linux-gnu- toolchain.

### ISSUE THREAD

**Issue by wangtao13** [apache/nuttx#19178]
### Description

I am working on nuttx-12.13 for a MIPS SOC, I just want to try module in nuttx, so I enable the `module` example in menuconfig and make it.  
Finally, I got an error as follows,
```
LD: nuttx
/home/t/develop/nuttx/staging/libc.a(elf_bind.o): In function `libelf_relocate':
elf/elf_bind.c:(.text+0x898): undefined reference to `up_relocate'
/home/t/develop/nuttx/staging/libc.a(elf_bind.o): In function `libelf_relocateadd':
elf/elf_bind.c:(.text+0xee4): undefined reference to `up_relocateadd'
/home/t/develop/nuttx/staging/libc.a(elf_bind.o): In function `libelf_relocatedyn':
elf/elf_bind.c:(.text+0x187c): undefined reference to `up_relocate'
/home/t/develop/nuttx/staging/libc.a(elf_verify.o): In function `libelf_verifyheader':
elf/elf_verify.c:(.text+0xb4): undefined reference to `up_checkarch'
make[1]: *** [Makefile:109: nuttx] Error 1
```
I did NOT find any definition of `up_checkarch()` and other undefined functions in arch/??

Thanks,

### Verification

- [x] I have verified before submitting the report.

**Comment by wangtao13** [comment]
I found the `up_checkarch` is defined in files in `libs/libc/machine/arch_name/arch_elf.c`, where the `arch_name` are:
```
x86
arm64
x86_64
risc-v
xtensa
sim
armv7-a
armv8-m
arm
armv7-r
armv7-m
armv8-r
armv6-m
```
It does NOT support `mips`.

So, how to add `mips` support to l`ibs/libc/machine/`?

**Comment by simbit18** [comment]
Hi @wangtao13, this is the MIPS toolchain we use in the Docker image

```
###############################################################################
# Build image for tool required by Pinguino builds
###############################################################################
FROM nuttx-toolchain-base AS nuttx-toolchain-pinguino
# Download the pinguino compilers. Note this includes both 8bit and 32bit
# toolchains and builds for multiple host systems. Only copy what is needed.
RUN mkdir -p pinguino-compilers && \
  curl -s -L "https://github.com/PinguinoIDE/pinguino-compilers/archive/62db5158d7f6d41c6fadb05de81cc31dd81a1958.tar.gz" \
  | tar -C pinguino-compilers --strip-components=2 --wildcards -xz */linux64
```

https://github.com/apache/nuttx/blob/master/tools/ci/docker/linux/Dockerfile#L180-L188

doc 
https://nuttx.apache.org/docs/latest/platforms/mips/index.html

**Comment by acassis** [comment]
@aviralgarg05 could you please take a look, maybe you have some suggestion since you are working with the dynamic loading and libelf

Update: I remember that @aviralgarg05 had this issue with SIMulator, in fact "up_relocate()" and others are not implemented for some arches. @wangtao13 you will need to implement these functions to MIPS.

Look at nuttx/libs/libc/machine/\*/\*/arch_elf.c for reference

**Comment by aviralgarg05** [comment]
From what I can see, the module loader is expecting the architecture to provide `up_checkarch()`, `up_relocate()`, and `up_relocateadd()`. Those hooks are implemented for a few other architectures under `libs/libc/machine/*/arch_elf.c`, but I’m not seeing the same support for MIPS. So this looks more like a missing piece of MIPS support in NuttX than a simple build/config issue on your side.

One small extra note: because you’re using `mips-linux-gnu-`, the toolchain may also matter here, since NuttX MIPS support is usually more aligned with bare-metal ELF toolchains. But even setting that aside, the immediate problem seems to be that the MIPS-side ELF relocation support for loadable modules just isn’t implemented yet.

So my honest read is: you’ve run into a gap in support, not a mistake in setup. If you want to get module loading working on MIPS, it will likely need a proper MIPS `arch_elf` implementation and the related build-system wiring. It may also be worth tightening Kconfig in the future so people get a clearer error earlier instead of hitting this at link time.

**Comment by acassis** [comment]
> From what I can see, the module loader is expecting the architecture to provide `up_checkarch()`, `up_relocate()`, and `up_relocateadd()`. Those hooks are implemented for a few other architectures under `libs/libc/machine/*/arch_elf.c`, but I’m not seeing the same support for MIPS. So this looks more like a missing piece of MIPS support in NuttX than a simple build/config issue on your side.
> 
> One small extra note: because you’re using `mips-linux-gnu-`, the toolchain may also matter here, since NuttX MIPS support is usually more aligned with bare-metal ELF toolchains. But even setting that aside, the immediate problem seems to be that the MIPS-side ELF relocation support for loadable modules just isn’t implemented yet.
> 
> So my honest read is: you’ve run into a gap in support, not a mistake in setup. If you want to get module loading working on MIPS, it will likely need a proper MIPS `arch_elf` implementation and the related build-system wiring. It may also be worth tightening Kconfig in the future so people get a clearer error earlier instead of hitting this at link time.

Thank you @aviralgarg05 that is my understanding as well.

@wangtao13 since MIPS is very similar to RISC-V, I think you can use RISC-V arch_elf as starting point. If you need help, please ask in the NuttX mailing list. You can find here the instructions to subscribe: https://nuttx.apache.org/community/

**Comment by wangtao13** [comment]
@acassis @aviralgarg05 Thank you for your comments and guidance.
So far, I am using the `mips-linux-gnu-` toolchain from MIPS SOC vendor which is used to build Linux kernel and other applications running in Linux.  I am not very familiar with `arch_elf.c` for other ARCHs, I can start with RISC-V, and may need your help in future.
I close this issue.
Thanks,
