### PR TITLE
{bp-19477} tools/Zig.defs: Fix Zig builds on sim:x86_64

### LINKED ISSUE #19475: [BUG] hello_zig fails to build on sim:x86_64 with Zig 0.13.0
## Description / Steps to reproduce the issue

While testing the Zig `hello_zig` example on `sim:x86_64`, I found that it cannot be built with Zig 0.13.0 due to two build issues.

### Steps to reproduce

1. Configure NuttX for `sim:x86_64`.
2. Enable the Zig hello example:
   ```
   CONFIG_EXAMPLES_HELLO_ZIG=y
   ```
3. Build NuttX.

The build first fails because `tools/Zig.defs` generates the following target:

```text
-target x86_64-freestanding-sysv
```

However, Zig reports:

```text
error: unknown ABI: 'sysv'
```

After locally changing the target to a Zig-supported ABI, the build proceeds further but then fails during linking with:

```text
undefined reference to `__zig_probe_stack'
```

The generated Zig object references `__zig_probe_stack`, but the required compiler runtime is not linked.

After applying local changes, the project builds successfully and the example runs correctly:

```text
NuttShell (NSH)

nsh> hello_zig
[sim]: Hello, Zig!
```

At this point I'm unsure what the preferred upstream approach is for addressing these two build issues, so I'm opening this issue first before preparing a patch.

---

### On which OS does this issue occur?

[OS: Linux]

### What is the version of your OS?

Ubuntu 24.04 LTS (WSL2)

### NuttX Version

master

### Issue Architecture

[Arch: x86], [Arch: x86_64]

### Issue Area

[Area: Build System]

## Host information

- Zig 0.13.0
- GCC host toolchain
- x86_64 Linux (WSL2)

### Verification

- [x] I have verified before submitting the report.

### PR DESCRIPTION
**Pull request by jerpelea**
## Summary

Building Zig applications on sim:x86_64 with Zig 0.13.0 fails because the generated target "x86_64-freestanding-sysv" is not recognized by Zig. Introduce a Zig-specific ABI mapping that translates "sysv" to "gnu" without affecting other toolchains.

After correcting the target ABI, linking still fails due to unresolved references to __zig_probe_stack. Add -fcompiler-rt so Zig includes the required compiler runtime during linking.

Verified on sim:nsh with CONFIG_EXAMPLES_HELLO_ZIG=y:

  nsh> hello_zig
  [sim]: Hello, Zig!

Fixes #19475

## Impact

RELEASE

## Testing

CI

### CODE REVIEW

**Review by xiaoxiang781216 — APPROVED** [review]

**Review by michallenc — APPROVED** [review]

**Comment by cederom** [comment]
-> releases/13.0 not 13.0.1 or 13.1.0 ? :-)

**Comment by jerpelea** [comment]
> -> releases/13.0 not 13.0.1 or 13.1.0 ? :-)

@cederom

13.0.1 fix release (ASAP)
13.1.0 minor release (end of September)

**Review by cederom — APPROVED** [review]
