### PR TITLE
rpmsg: Handle the dependence correctly

### PR DESCRIPTION
**Pull request by xiaoxiang781216**
## Summary

1.Let RPMSG_VIRTIO_LITE select RPMSG_VIRTIO
2.Let RPMSG_VIRTIO_IVSHMEM select RPMSG_VIRTIO_LITE

## Impact

fix https://github.com/apache/nuttx/pull/15336

## Testing

ci

### CODE REVIEW

**Comment by nuttxpr** [comment]
[**\[Experimental Bot, please feedback here\]**](https://github.com/search?q=repo%3Aapache%2Fnuttx+13552&type=issues)



No, this PR description does not fully meet the NuttX requirements. While it provides a basic summary and mentions testing through CI, it lacks crucial details.

Here's what's missing:

* **Summary:**  While it states *what* is changed, it doesn't explain *why*.  What problem does this solve? Why is selecting RPMSG_VIRTIO necessary in these cases?  How does this selection mechanism work?  A link to the original PR (#15336) helps, but the description itself should be self-contained enough to understand the core change.

* **Impact:**  The PR claims to be a fix, which implies existing functionality was broken.  Therefore, several "Impact" sections should be addressed.  At a minimum:
    * **Is existing feature changed?** - YES (explicitly state this).
    * **Impact on user:**  Potentially YES.  If this fixes a bug, users relying on the broken functionality will see a change in behavior.  This needs to be described.
    * **Impact on hardware:** Possibly YES, depending on which architectures/boards use this functionality. Specify if any particular hardware configurations are affected.
    * **Impact on compatibility:**  Possibly YES, again depending on the nature of the fix.  Does this break compatibility with any existing configurations or applications?
    * The other "Impact" sections might also be relevant depending on the specific changes.  Even if the answer is NO, it's better to explicitly state it for clarity.


* **Testing:**  "ci" is insufficient.  While CI testing is important, the description should include specific details about *what* was tested.  Ideally, provide snippets of logs or output demonstrating the issue before the change and the corrected behavior after the change.  What platforms (Build Host and Target) were these tests run on?


**Example of an improved summary:**

"This PR fixes a configuration issue introduced in #15336 where enabling RPMSG_VIRTIO_LITE or RPMSG_VIRTIO_IVSHMEM did not automatically enable the required RPMSG_VIRTIO option.  This resulted in build failures or runtime errors when using these features. This change adds the necessary Kconfig dependencies to ensure RPMSG_VIRTIO is selected when either of the lighter-weight options are enabled."

**Example of improved testing information:**

"Build Host: Linux (Ubuntu 22.04), x86_64, GCC 11.3.0
Target: QEMU-RISCV64, virt board configuration

Testing logs before change (demonstrating build failure):

```
... error: undefined reference to 'some_rpmsg_virtio_function' ...
```

Testing logs after change (demonstrating successful build and basic functionality):

```
... system booted successfully ...
... rpmsg communication test passed ...
```"


By adding these details, the PR will be much easier to review and understand, increasing its chances of being accepted.
