### PR TITLE
h743zi/capture: add doc, defconfig & update make pipeline

### PR DESCRIPTION
**Pull request by comejv**
## Summary

Add documentation for changes made in #16809 and the upper-half driver for timer capture.
Add an example defconfig for a nsh build with the capture example.

## Impact

Becomes easier to start doing timer capture on all boards.

## Testing

Built documentation with `make html`.

### CODE REVIEW

**Comment by comejv** [comment]
Failed check will be fixed by #16827

**Comment by xiaoxiang781216** [comment]
please fix the build error:
```
Error: stm32_bringup.c:109:7: error: too few arguments to function 'stm32_cap_initialize'
  109 |       stm32_cap_initialize(4),
      |       ^~~~~~~~~~~~~~~~~~~~
In file included from stm32_bringup.c:62:
/github/workspace/sources/nuttx/arch/arm/src/chip/stm32_capture.h:231:25: note: declared here
  231 | struct cap_lowerhalf_s *stm32_cap_initialize(int timer, uint8_t channel);
      |                         ^~~~~~~~~~~~~~~~~~~~
```

File: Documentation/components/drivers/character/timers/capture.rst [hunk 1]
```diff
@@ -0,0 +1,138 @@
...
+Supported ``ioctl`` Commands
+----------------------------
+
+.. c:macro:: CAPIOC_DUTYCYCLE
+
+   Get the PWM duty cycle from the capture unit.
+
+   **Argument:** ``int8_t *`` (pointer to duty cycle percentage).
+
+.. c:macro:: CAPIOC_FREQUENCE
```
Comment (acassis) [inline Documentation/components/drivers/character/timers/capture.rst:27]: @comejv I think we missed that in your PR: "Frequence" is not a standard English word, please replace with Frequency

Comment (comejv) [reply Documentation/components/drivers/character/timers/capture.rst:27]: I noticed too but it is what's use in all other drivers, I think it would be best to do a different PR to change it repo wise

Comment (comejv) [reply Documentation/components/drivers/character/timers/capture.rst:27]: Actually it's only two files, the upper half capture driver source and header, should I do it in this PR?

Comment (comejv) [reply Documentation/components/drivers/character/timers/capture.rst:27]: We would have to update https://github.com/apache/nuttx-apps/blob/master/examples%2Fcapture%2Fcap_main.c too, because changing the macro would be a breaking change

**Comment by comejv** [comment]
Closed by mistake (deleted my branch)

**Comment by comejv** [comment]
Rebased on master to add fix from #16827

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by comejv** [comment]
I think I found the issue, no idea why it built on my end, I'll fix it.

It's probably because the capture defconfig was lacking CONFIG_STM32H7_CAP, which is weird because it should have been included by setting TIM4_CAP which depends on it:
```
config STM32H7_TIM4_CAP
	bool "TIM4 Capture"
	default n
	depends on STM32H7_TIM4
	select STM32H7_CAP
	---help---
		Reserve timer 4 for use by the capture driver.
```

**Comment by comejv** [comment]
Still can't reproduce, even when on a clean branch...
```shell
git branch -D doc/h743zicapture
git switch -c doc/h743zicapture --track perso/doc/h743zicapture
```

This should let me be in the same state as this PR right?

**Comment by xiaoxiang781216** [comment]
> Still can't reproduce, even when on a clean branch...
> 
> ```shell
> git branch -D doc/h743zicapture
> git switch -c doc/h743zicapture --track perso/doc/h743zicapture
> ```
> 
> This should let me be in the same state as this PR right?

please add a new patch to fix the issue in this pr, we can't merge the patch which can't pass ci.

**Comment by comejv** [comment]
I got it! I only updated the cmake pipeline, forgot about the makefiles. Will push one last time.

**Review by xiaoxiang781216 — APPROVED** [review]

**Review by jerpelea — APPROVED** [review]
