### PR TITLE
Fix Error: board/esp32c3_bringup.c:150:9: error: implicit declaration of function 'board_apds9960_initialize'

### PR DESCRIPTION
**Pull request by xiaoxiang781216**
## Summary

Fix the ci broken reported here due to https://github.com/apache/nuttx/pull/7832:
https://github.com/apache/nuttx/actions/runs/3652785945/jobs/6171593013

## Impact
boards/risc-v/litex/arty_a7

## Testing
Pass CI

### CODE REVIEW

**Review by pkarashchenko — APPROVED** [review]

**Comment by xiaoxiang781216** [comment]
@gustavonihei do you have better idea to fix riscv ci broken? I am out of idea.

**Comment by gustavonihei** [comment]
> @gustavonihei do you have better idea to fix riscv ci broken? I am out of idea.

I am away from PC right now, but looking at the logs, it seems that some ESP32-C3 defconfigs are not properly cleaning the workspace and the CI is failing due to leftover files.

**Comment by xiaoxiang781216** [comment]
The real problem is 32/64 mismatch:
image

**Comment by gustavonihei** [comment]
> The real problem is 32/64 mismatch: image

Sorry, you're right.

The problem is that `--print-libgcc-file-name` and `--print-file-name=libm.a` are returning the paths for the RV64 version of the `libgcc.a` and `libm.a` files.

**Comment by xiaoxiang781216** [comment]
@gustavonihei should we report the bug to sifive? Before it gets fixed, let's disable arty_a7 from ci temporally.
