### ISSUE TITLE
[BUG] cmath incompatible with external toolchain libraries

### ISSUE THREAD

**Issue by snikeguo** [apache/nuttx#18232]
### Description / Steps to reproduce the issue

nvironment:

NuttX + arm-none-eabi-gcc 13.3.1
Must use toolchain's standard math and C++ libraries (not NuttX's built-in versions /llvm /uclib/nuttx math lib):
```
CONFIG_LIBM_TOOLCHAIN=y
CONFIG_LIBCXXTOOLCHAIN=y
CONFIG_LIBSUPCXX_TOOLCHAIN=y
```

demo:
```
#include <stdint.h>
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>

int main() { 
    return 0; 
}
```
build log:
```
In file included from D:/Soft/ArmGcc/xpack-arm-none-eabi-gcc-13.3.1-1.1/arm-none-eabi/include/c++/13.3.1/math.h:36,
                 from D:/Project/runtime_nuttx/src/nuttx_workspace/apps/ics/NativeAot/user_code/usercode.cpp:177:
D:/Project/runtime_nuttx/src/nuttx_workspace/nuttx/include/cxx/cmath:47:11: error: 'float_t' has not been declared in '::'
   47 |   using ::float_t;
      |           ^~~~~~~
D:/Project/runtime_nuttx/src/nuttx_workspace/nuttx/include/cxx/cmath:48:11: error: 'double_t' has not been declared in '::'
   48 |   using ::double_t;
      |           ^~~~~~~~
D:/Project/runtime_nuttx/src/nuttx_workspace/nuttx/include/cxx/cmath:51:11: error: 'acosf' has not been declared in '::'
   51 |   using ::acosf;
```

### On which OS does this issue occur?

[OS: Windows]

### What is the version of your OS?

win11

### NuttX Version

mastere

### Issue Architecture

[Arch: arm]

### Issue Area

[Area: OS Components]

### Verification

- [x] I have verified before submitting the report.

**Comment by adwait-godbole** [comment]
working on this. trying to reproduce it locally.

**Comment by aviralgarg05** [comment]
I would like to solve this issue, please assign me

**Comment by xiaoxiang781216** [comment]
> I would like to solve this issue, please assign me

Done, thanks.

**Comment by simbit18** [comment]
Hi @snikeguo, this PR https://github.com/apache/nuttx/pull/18308 has been merged. Does that solve your issue ?

**Comment by snikeguo** [comment]
> Hi [@snikeguo](https://github.com/snikeguo), this PR [#18308](https://github.com/apache/nuttx/pull/18308) has been merged. Does that solve your issue ?

@simbit18 
no，demo code:

```

#include <stdint.h>
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <wchar.h>
#include <assert.h>
#include <stdarg.h>
#include <memory.h>
#include <limits.h>
#include <math.h>

#include <new>
#include <type_traits>
#include <limits>
#include <algorithm>
#include <pthread.h>
using namespace std;

int foo(){}

```

common config:
```
CONFIG_HAVE_CXX=y
CONFIG_HAVE_CXXINITIALIZE=y
CONFIG_LIBCXXTOOLCHAIN=y
CONFIG_LIBSUPCXX_TOOLCHAIN=y
```

.config:
```
CONFIG_LIBM=y  # use nuttx math lib
```
build ok .

.config:
```
CONFIG_LIBM_TOOLCHAIN=y # use tool chain libm
```
build failed:
```
In file included from D:/Project/runtime_nuttx/src/nuttx_workspace/apps/ics/NativeAot/user_code/usercode.cpp:220:
D:/Soft/ArmGcc/xpack-arm-none-eabi-gcc-13.3.1-1.1/arm-none-eabi/include/c++/13.3.1/math.h:38:12: error: 'abs' has not been declared in 'std'
   38 | using std::abs;
      |            ^~~
D:/Soft/ArmGcc/xpack-arm-none-eabi-gcc-13.3.1-1.1/arm-none-eabi/include/c++/13.3.1/math.h:39:12: error: 'acos' has not been declared in 'std'
   39 | using std::acos;
      |            ^~~~
D:/Soft/ArmGcc/xpack-arm-none-eabi-gcc-13.3.1-1.1/arm-none-eabi/include/c++/13.3.1/math.h:40:12: error: 'asin' has not been declared in 'std'
   40 | using std::asin;
```

**Comment by simbit18** [comment]
Hi @aviralgarg05, could you please check?

**Comment by aviralgarg05** [comment]
> Hi [@aviralgarg05](https://github.com/aviralgarg05), could you please check?

Ok I'll go through this

**Comment by aviralgarg05** [comment]
I investigated the remaining `CONFIG_LIBM_TOOLCHAIN=y` failure after #18308 and opened a follow-up fix PR: #18374.

This updates `include/cxx/cmath` to delegate to toolchain `<cmath>` when using toolchain libm, which resolves the `std::abs/std::acos/...` errors reported here:
https://github.com/apache/nuttx/issues/18232#issuecomment-3861302869

Could you please retest with PR #18374?

**Comment by acassis** [comment]
@snikeguo could you please verify if the solution created by @aviralgarg05 fixed your issue?

**Comment by simbit18** [comment]
Hi @snikeguo, does this PR #18374 resolve your issue?

**Comment by snikeguo** [comment]
@acassis  @simbit18  
I am very sorry, I was on vacation recently.after testing, the compilation still fails. Here are the test code and compilation results:
```
#include <stdint.h>
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <wchar.h>
#include <assert.h>
#include <stdarg.h>
#include <memory.h>
#include <limits.h>
#include <math.h>

#include <new>
#include <type_traits>
#include <limits>
#include <algorithm>


D:/Project/runtime_nuttx/src/nuttx_workspace/apps/ics/NativeAot/user_code/usercode.cpp
In file included from D:/Soft/ArmGcc/xpack-arm-none-eabi-gcc-13.3.1-1.1/arm-none-eabi/include/c++/13.3.1/bits/std_abs.h:38,
                 from D:/Soft/ArmGcc/xpack-arm-none-eabi-gcc-13.3.1-1.1/arm-none-eabi/include/c++/13.3.1/cmath:49,
                 from D:/Project/runtime_nuttx/src/nuttx_workspace/nuttx/include/cxx/cmath:38,
                 from D:/Soft/ArmGcc/xpack-arm-none-eabi-gcc-13.3.1-1.1/arm-none-eabi/include/c++/13.3.1/math.h:36,
                 from D:/Project/runtime_nuttx/src/nuttx_workspace/apps/ics/NativeAot/user_code/usercode.cpp:221:
D:/Soft/ArmGcc/xpack-arm-none-eabi-gcc-13.3.1-1.1/arm-none-eabi/include/stdlib.h:39:3: error: conflicting declaration 'typedef struct div_t div_t'
   39 | } div_t;
      |   ^~~~~
In file included from D:/Project/runtime_nuttx/src/nuttx_workspace/nuttx/include/nuttx/kmalloc.h:34,
                 from D:/Project/runtime_nuttx/src/nuttx_workspace/nuttx/include/nuttx/lib/lib.h:32,
                 from D:/Project/runtime_nuttx/src/nuttx_workspace/nuttx/include/stdio.h:37,
                 from D:/Project/runtime_nuttx/src/nuttx_workspace/apps/include/netutils/netlib.h:50,
                 from D:/Project/runtime_nuttx/src/nuttx_workspace/apps/ics/NativeAot/user_code/usercode.cpp:105:
D:/Project/runtime_nuttx/src/nuttx_workspace/nuttx/include/stdlib.h:98:22: note: previous declaration as 'typedef struct div_s div_t'
   98 | typedef struct div_s div_t;
```

It is worth noting that I have switched to using the LLVM C++ library, and it works well.

**Comment by aviralgarg05** [comment]
@snikeguo So this is now a `stdlib` header collision in the toolchain C++ path, not the previous `cmath` import issue.

I can take this as a follow-up fix target and prepare an update for the GCC/libstdc++ path so `CONFIG_LIBM_TOOLCHAIN=y + CONFIG_LIBCXXTOOLCHAIN=y` works cleanly without this `div_t` conflict. 
@acassis  @simbit18 , your thoughts on this?
