### PR TITLE
arm/efm32: fix regression by PR#14810

### PR DESCRIPTION
**Pull request by anchao**
## Summary

1. arm/efm32: fix regression by PR #14810
2. arm/cortex-m: itm syslog should select SYSLOG_REGISTER
3. arm/efm: fix build warning
```
chip/efm32_start.c:150:3: warning: implicit declaration of function 'itm_syslog_initialize';
                                   did you mean 'syslog_initialize'? [-Wimplicit-function-declaration]
  150 |   itm_syslog_initialize();
      |   ^~~~~~~~~~~~~~~~~~~~~
      |   syslog_initialize
```
4. arm/efm32: fix build break caused by undeclared error

Old upstream from @acassis:
https://github.com/acassis/nuttx/blob/d97227eddd96713870875f33b6a4a2ebad10db0b/nuttx/configs/efm32gg-pnbfano/include/board.h

```
chip/efm32_clockconfig.c:860:24: error: 'BOARD_SWOPORT_LOCATION' undeclared (first use in this function);
                                 did you mean 'BOARD_UART0_ROUTE_LOCATION'?
  860 |   regval |= ((uint32_t)BOARD_SWOPORT_LOCATION <<
      |                        ^~~~~~~~~~~~~~~~~~~~~~
      |                        BOARD_UART0_ROUTE_LOCATION
chip/efm32_clockconfig.c:860:24: note: each undeclared identifier is reported only once for each function it appears in
chip/efm32_clockconfig.c:866:20: error: 'BOARD_GPIO_SWOPORT' undeclared (first use in this function)
  866 |   efm32_configgpio(BOARD_GPIO_SWOPORT);
      |                    ^~~~~~~~~~~~~~~~~~
```

## Impact

N/A

## Testing

./tools/configure.sh efm32gg-stk3700/nsh

### CODE REVIEW

**Comment by nuttxpr** [comment]
[**\[Experimental Bot, please feedback here\]**](https://github.com/search?q=repo%3Aapache%2Fnuttx+13552&type=issues)



This PR summary doesn't adequately address the NuttX requirements. Here's a breakdown of what's missing and how to improve it:

**Problems with the current Summary:**

* **Lack of Explanation:** Simply listing changes isn't enough.  *Why* are these changes necessary? What problem do they solve? What benefit do they provide?  For example, "arm/efm32: fix regression by PR#14810" needs more context. What was the regression? How does this PR fix it?
* **Missing Detail:** "arm/efm: fix build warning" and "arm/efm32: fix build break" are too vague. What specific warnings/errors were encountered? How were they resolved?  Providing the actual error message is good, but also explain the *root cause* of the error.
* **Unclear Functionality:**  "arm/cortex-m: itm syslog should select SYSLOG_REGISTER" – What does this mean functionally? Why is this selection necessary?  What happens if it's not selected?

**How to Improve the Summary:**

1. **Expand on each point:**
    * **Regression Fix:** Explain the original issue caused by PR#14810, the symptoms of the regression, and how this PR addresses the root cause of the problem.
    * **SYSLOG_REGISTER:** Explain why `itm_syslog_initialize()` requires `SYSLOG_REGISTER` to be selected. What functionality depends on this?  What were the consequences of it not being selected?
    * **Build Warning/Error Fixes:** Describe why the implicit declaration of `itm_syslog_initialize()` occurred.  Why was `BOARD_SWOPORT_LOCATION` and `BOARD_GPIO_SWOPORT` undeclared?  Explain the solution implemented to fix these issues (e.g., adding header files, defining missing macros, etc.).

2. **Consolidate if Possible:** If all these changes relate to a single underlying issue, consider presenting them as one cohesive change with sub-points.

**Problems with the Impact Section:**

* **"N/A" is insufficient:**  Even if you believe there's no user-facing impact, explicitly state that. For example: "Impact on user: NO. This change only affects internal code and has no impact on user functionality."  Do this for *every* impact category.  Even if the answer is NO, justify it briefly.

**How to Improve the Impact Section:**

* **Address each point individually:** Go through each impact category (user, build, hardware, documentation, security, compatibility) and explicitly state whether there's an impact (YES/NO) and provide a brief justification.  Even if the answer is NO, explain why.

**Problems with the Testing Section:**

* **Insufficient Testing Information:** Simply stating the configuration used isn't enough.  What tests were performed? What were the expected results?  The provided logs are empty, so there's no evidence that testing was actually done.

**How to Improve the Testing Section:**

* **Detailed Test Cases:** Describe the specific tests performed to verify the changes.  For example: "Built and ran the NSH configuration on the efm32gg-stk3700. Verified that [specific functionality related to the fix] works as expected."
* **Meaningful Logs:** Include relevant log output *before* and *after* the change to demonstrate the issue and the fix.  Highlight the relevant parts of the logs.  If the logs are too long, consider providing snippets or summarizing the key differences.
* **Multiple Targets (if applicable):** If the change affects multiple architectures or boards, provide testing results for each.


By providing more detailed explanations and evidence of testing, you can create a much stronger PR that is more likely to be accepted. Remember, the goal is to clearly communicate the changes, their impact, and how they've been validated.

**Review by xiaoxiang781216 — APPROVED** [review]

**Review by jerpelea — APPROVED** [review]
