### PR TITLE
sched/irq: spinlock should not depends on SMP

### PR DESCRIPTION
**Pull request by anchao**
## Summary

sched/irq: spinlock should not depends on SMP

spinlock should work independently without CONFIG_SMP

Signed-off-by: chao an <anchao@lixiang.com>

## Impact

N/A

## Testing

ci-check

### CODE REVIEW

**Review by xiaoxiang781216 — APPROVED** [review]

**Review by pkarashchenko — APPROVED** [review]

**Comment by pkarashchenko** [comment]
```
====================================================================================
Configuration/Tool: esp32c3-devkit/ble
------------------------------------------------------------------------------------
  Cleaning...
  Configuring...
  Building NuttX...
semaphore/spinlock.c: In function 'spin_lock':
Error: semaphore/spinlock.c:84:10: error: implicit declaration of function 'up_testset'; did you mean 'up_getsp'? [-Werror=implicit-function-declaration]
   84 |   while (up_testset(lock) == SP_LOCKED)
      |          ^~~~~~~~~~
      |          up_getsp
cc1: all warnings being treated as errors
make[1]: *** [Makefile:61: spinlock.o] Error 1
make[1]: Target 'libsched.a' not remade because of errors.
make: *** [tools/LibTargets.mk:65: sched/libsched.a] Error 2
make: Target 'all' not remade because of errors.
```

**Review by acassis — APPROVED** [review]

**Review by xiaoxiang781216 — APPROVED** [review]
