### ISSUE TITLE
[BUG] lpcxpresso-lpc54628/nsh fails to build: 'priv' is used uninitialized (spin_lock_irqsave)

### ISSUE THREAD

**Issue by lupyuen** [apache/nuttx#15679]
### Description / Steps to reproduce the issue

`lpcxpresso-lpc54628:nsh` fails to build with a Spin Lock Error:

https://github.com/NuttX/nuttx/actions/runs/12935919991/job/36080453959#step:7:570
```text
Configuration/Tool: lpcxpresso-lpc54628/nsh,CONFIG_ARM_TOOLCHAIN_CLANG
chip/lpc54_i2c_master.c: In function 'lpc54_i2cbus_initialize':
Error: chip/lpc54_i2c_master.c:917:29: error: 'priv' is used uninitialized [-Werror=uninitialized]
  917 |   flags = spin_lock_irqsave(&priv->spinlock);
      |                             ^~~~~~~~~~~~~~~
chip/lpc54_i2c_master.c:911:26: note: 'priv' was declared here
  911 |   struct lpc54_i2cdev_s *priv;
      |                          ^~~~
```

NuttX Build History says that the Breaking Commit is somewhere between these 2 commits:
- Good Commit: https://github.com/apache/nuttx/pull/15673
- Bad Commit: https://github.com/apache/nuttx/pull/15648

_https://nuttx-dashboard.org/d/fe2q876wubc3kc/nuttx-build-history?from=now-7d&to=now&timezone=browser&var-arch=$__all&var-subarch=$__all&var-board=lpcxpresso-lpc54628&var-config=nsh&var-group=$__all&var-Filters=_

![Image](https://github.com/user-attachments/assets/7207ae61-ddc8-459b-9ae6-f3de0cd1d920)

NuttX Dashboard shows other similar errors:

_https://nuttx-dashboard.org/d/fe2bqg6uk7nr4a/build-logs-from-nuttx-build-farm?from=now-2d&to=now&timezone=browser&var-arch=$__all&var-subarch=$__all&var-board=$__all&var-config=$__all&var-group=$__all&var-Filters=user%7C%3D%7CNuttX_

![Image](https://github.com/user-attachments/assets/812e5d48-2b90-4fac-b8c7-803ba4d63f04)

### On which OS does this issue occur?

[OS: Linux]

### What is the version of your OS?

Ubuntu LTS at GitHub CI

### NuttX Version

master

### Issue Architecture

[Arch: arm]

### Issue Area

[Area: Board support]

### Verification

- [x] I have verified before submitting the report.
