### PR TITLE
{Bp-13639} sensor:Update sensor type

### PR DESCRIPTION
**Pull request by jerpelea**
##Summary
Sort the existing sensor types and align them to aosp
Add sensor info to get structure, align parameters with aosp
Add some sensor types in aosp.

##Impact
RELEASE

##Testing 
CI

### CODE REVIEW

**Review by lupyuen — APPROVED** [review]

**Comment by lupyuen** [comment]
Oops sim-01 fails with the GPIO issue from https://github.com/apache/nuttx/pull/13792
```text
Error: gpio_main.c:317:12: error: 'GPIO_INTERRUPT_PIN_WAKEUP' undeclared (first use in this function); did you mean 'GPIO_INTERRUPT_PIN'?
  317 |       case GPIO_INTERRUPT_PIN_WAKEUP:
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~
      |            GPIO_INTERRUPT_PIN
```
https://github.com/apache/nuttx/actions/runs/11144479935/job/30971929929?pr=13793

**Review by Donny9 — APPROVED** [review]

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by raiden00pl** [comment]
@jerpelea this PR on apps side must be included in release: https://github.com/apache/nuttx-apps/pull/2603 otherwise we'll get compilation errors.
