### PR TITLE
rptun ping: fix warning when open CONFIG_SYSTEM_TIME64

### PR DESCRIPTION
**Pull request by GUIDINGLI**
## Summary

rptun ping: fix warning when open CONFIG_SYSTEM_TIME64

rptun/rptun_ping.c: In function 'rptun_ping':
rptun/rptun_ping.c:171:20: error: format '%lu' expects argument of type 'long unsigned int', but argument 3 has type 'time_t' {aka 'long long int'} [-Werror=format=]
  171 |   syslog(LOG_INFO, "avg: s %" PRIu32 ", ns %ld\n", ts.tv_sec, ts.tv_nsec);
      |                    ^~~~~~~~~~                      ~~~~~~~~~
      |                                                      |
      |

## Impact

rptun

### CODE REVIEW

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by xiaoxiang781216** [comment]
Let's ignore the unrelated ci broken which is fixed by https://github.com/apache/nuttx/pull/8155.
